# Generated by Django 5.0 on 2023-12-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=6,
            ),
        ),
    ]
