# Generated by Django 5.0 on 2023-12-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_user", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="interests",
            field=models.ManyToManyField(
                blank=True, db_index=True, to="app_user.interest"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.IntegerField(db_index=True, max_length=10, unique=True),
        ),
    ]
