# Generated by Django 5.0 on 2023-12-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_user", "0003_alter_user_email_alter_user_interests_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
