# Generated by Django 5.0 on 2023-12-06 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_user", "0005_user_current_connection_user_is_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="current_connection",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="connected_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
