# Generated by Django 5.0 on 2023-12-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_user", "0006_alter_user_current_connection_alter_user_is_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="interests",
            field=models.ManyToManyField(
                db_index=True, null=True, to="app_user.interest"
            ),
        ),
    ]
