# Generated by Django 5.0 on 2023-12-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_user", "0007_alter_user_interests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interest",
            name="name",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
