# Generated by Django 5.0 on 2023-12-06 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_user", "0009_alter_user_current_connection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="current_connection",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="connected_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="interests",
            field=models.ManyToManyField(db_index=True, to="app_user.interest"),
        ),
    ]
